# Databricks notebook source
# ════════════════════════════════════════════════════════════════════════
# SAP S/4HANA (Datasphere replication flow) → Bronze → Silver
# Config-driven Lakeflow Declarative Pipeline
#
# Gold is NOT built here: gold tables join and transform several silver
# tables and need MERGE / multi-step SQL, so they run in the separate
# sap_gold notebook (next job task). Gold layers (layer_type=spark) in the
# config are ignored by this pipeline.
#
# Pipeline configuration (Settings → Advanced → Configuration):
#   pipeline_id      REQUIRED  pipeline_name from pipeline_table_config
#   environment      REQUIRED  dev | qa | prod
#   ctrl_schema      optional  control-table schema written by the registry
#                              (default rgaplxdatabricks.uct_demo)
#   base_volume      optional  framework volume holding configs/, schema/, logs/
#   config_out_dir   optional  default {base_volume}/configs
#   archive_after    optional  cleanSource wait before moving files (default "7 days")
#
# Layers, as generated by pipeline_register:
#   bronze  layer_type=dlt   dlt_mode=bronze   streaming table via Auto Loader
#   silver  layer_type=dlt   dlt_mode=snapshot streaming mirror   (load_type full)
#                            dlt_mode=delta    streaming append   (load_type delta)
#                            dlt_mode=upsert   auto CDC, SCD1     (load_type scd1)
#                            dlt_mode=history  auto CDC, SCD2     (load_type scd2)
#   gold    layer_type=spark                   skipped — built by the sap_gold notebook
#
# This file only DEFINES datasets. DDL/DML is rejected inside a pipeline
# source file, so gold, run history and reconciliation are written by
# notebooks that run after this pipeline in the same job.
# ════════════════════════════════════════════════════════════════════════

import os
import re
import json
from datetime import datetime

from pyspark import pipelines as dp
from pyspark.sql.functions import coalesce, col, current_timestamp, expr, struct

# COMMAND ----------

# ── 0. Pipeline configuration + logging ─────────────────────────────────

def _conf(key: str, default: str = "", required: bool = False) -> str:
    val = (spark.conf.get(key, default) or "").strip()
    if required and not val:
        raise ValueError(
            f"Pipeline configuration key '{key}' is required. Set it under "
            f"Pipeline settings → Advanced → Configuration.")
    return val


PIPELINE_ID    = _conf("pipeline_id", required=True)
ENVIRONMENT    = _conf("environment", required=True).lower()
CTRL           = _conf("ctrl_schema", "rgaplxdatabricks.uct_demo")
BASE_VOLUME    = _conf("base_volume", "/Volumes/rgaplxdatabricks/temp_source/source_files").rstrip("/")
CONFIG_OUT_DIR = _conf("config_out_dir", f"{BASE_VOLUME}/configs").rstrip("/")
ARCHIVE_AFTER  = _conf("archive_after", "7 days")
LOG_DIR        = f"{BASE_VOLUME}/logs"

if ENVIRONMENT not in ("dev", "qa", "prod"):
    raise ValueError(f"environment must be dev|qa|prod — got '{ENVIRONMENT}'")

COMPONENT      = "LAKEFLOW"
_LOG_LINES     = []
_LOG_FILE_PATH = None


def _flush_log():
    # Volumes are FUSE-mounted and don't support append mode ("a" needs a
    # seek), so the whole file is rewritten from the in-memory buffer.
    if not _LOG_FILE_PATH:
        return
    try:
        with open(_LOG_FILE_PATH, "w") as f:
            f.write("\n".join(_LOG_LINES) + "\n")
    except Exception as ex:
        print(f"WARNING: could not write log file {_LOG_FILE_PATH}: {ex}")


def log(stage: str, message: str, level: str = "INFO"):
    line = f"{datetime.now():%Y-%m-%d %H:%M:%S} [{level}] [{COMPONENT}] [{stage}] {message}"
    print(line)
    _LOG_LINES.append(line)
    _flush_log()


def _open_shared_log(generated_at: str):
    """The log file is named after the config's generated_at, so this
    pipeline and pipeline_audit write to the same file. Lines already in
    the file are kept, not overwritten."""
    global _LOG_FILE_PATH
    path = f"{LOG_DIR}/{PIPELINE_ID}_{ENVIRONMENT}_{generated_at}.log"
    try:
        os.makedirs(LOG_DIR, exist_ok=True)
        if os.path.exists(path):
            with open(path) as f:
                existing = f.read().rstrip("\n")
            if existing:
                _LOG_LINES[:0] = existing.split("\n")
        _LOG_FILE_PATH = path
        _flush_log()
    except Exception as ex:
        print(f"WARNING: could not open log file {path}: {ex}")

# COMMAND ----------

# ── 1. Resolve and load the config ──────────────────────────────────────

_FNAME_RE = re.compile(
    rf"^{re.escape(PIPELINE_ID)}_{re.escape(ENVIRONMENT)}_(\d{{8}}_\d{{6}})_config\.json$")


def resolve_config_path():
    """The pipeline_config_versions row marked 'current' is authoritative:
    the registry writes the file first and marks it current second, so a
    newer file without a 'current' row is a failed registration. Falls
    back to the newest timestamped file if the table can't be read."""
    try:
        rows = spark.sql(
            f"""SELECT config_path FROM {CTRL}.pipeline_config_versions
                WHERE pipeline_id = :p AND environment = :e AND version_status = 'current'
                ORDER BY version_number DESC LIMIT 1""",
            args={"p": PIPELINE_ID, "e": ENVIRONMENT}).collect()
        if rows and rows[0]["config_path"]:
            return rows[0]["config_path"], "pipeline_config_versions (current)"
    except Exception as ex:
        log("CONFIG", f"Could not read {CTRL}.pipeline_config_versions: {ex}", "WARNING")

    folder = f"{CONFIG_OUT_DIR}/{PIPELINE_ID}"
    try:
        entries = dbutils.fs.ls(folder)
    except Exception as ex:
        raise FileNotFoundError(f"Could not list config folder '{folder}': {ex}")
    candidates = sorted((m.group(1), e.path) for e in entries if (m := _FNAME_RE.match(e.name)))
    if not candidates:
        raise FileNotFoundError(
            f"No config '{PIPELINE_ID}_{ENVIRONMENT}_<timestamp>_config.json' in {folder}. "
            f"Run the metadata loader first.")
    return candidates[-1][1], "newest file in config folder (fallback)"


config_path, config_origin = resolve_config_path()
config = json.loads(spark.read.text(config_path, wholetext=True).first()[0])

if config.get("pipeline_id") != PIPELINE_ID or config.get("environment") != ENVIRONMENT:
    raise ValueError(
        f"Config {config_path} is for {config.get('pipeline_id')}/{config.get('environment')}, "
        f"not {PIPELINE_ID}/{ENVIRONMENT}")

_open_shared_log(config.get("generated_at") or datetime.now().strftime("%Y%m%d_%H%M%S"))
log("CONFIG", f"pipeline_id={PIPELINE_ID} environment={ENVIRONMENT}")
log("CONFIG", f"Config v{config.get('version_number', '?')}: {config_path} (from {config_origin})")

# COMMAND ----------

# ── 2. Helpers ──────────────────────────────────────────────────────────

DDL_TYPE_MAP = {
    "string": "STRING", "long": "BIGINT", "bigint": "BIGINT", "integer": "INT",
    "int": "INT", "double": "DOUBLE", "float": "FLOAT", "boolean": "BOOLEAN",
    "timestamp": "TIMESTAMP", "timestamp_ntz": "TIMESTAMP_NTZ", "date": "DATE",
    "binary": "BINARY",
}
_DECIMAL_RE = re.compile(r"^decimal\(\s*\d+\s*,\s*\d+\s*\)$", re.IGNORECASE)
_PLAIN_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Types Delta can store. Anything else Auto Loader produces is dropped.
SUPPORTED_TYPES = {
    "StringType", "LongType", "IntegerType", "ShortType", "ByteType",
    "DoubleType", "FloatType", "DecimalType", "BooleanType", "DateType",
    "TimestampType", "TimestampNTZType", "BinaryType", "NullType",
}

# Datasphere system columns. Files for the same table have been seen with
# different casing (__timestamp vs __Timestamp); with column mapping on,
# those would become two physical columns, so every variant is collapsed
# onto one lowercase name with one type right after the read.
SYSTEM_COL_CASTS = {
    "__timestamp":       "timestamp_ntz",
    "__operation_type":  "string",
    "__sequence_number": "decimal(20,0)",
}


def _ddl_type(t: str):
    t = (t or "").strip().lower()
    if _DECIMAL_RE.match(t):
        return t.upper().replace(" ", "")
    return DDL_TYPE_MAP.get(t)


def schema_to_hints(schema_dict) -> str:
    """Config schema → cloudFiles.schemaHints. Columns with unsupported
    types are left to parquet inference. SAP names such as /BIC/FIELD are
    backtick-quoted."""
    parts = []
    for f in (schema_dict or {}).get("fields", []):
        typ = _ddl_type(f.get("type"))
        if typ is None:
            log("SCHEMA_HINTS", f"Skipping {f.get('name')} ({f.get('type')}): unsupported type", "WARNING")
            continue
        name = f["name"] if _PLAIN_IDENT_RE.match(f["name"]) else f"`{f['name']}`"
        parts.append(f"{name} {typ}")
    return ", ".join(parts)


def normalize_system_columns(df):
    for canonical, cast_type in SYSTEM_COL_CASTS.items():
        variants = [f.name for f in df.schema.fields if f.name.lower() == canonical]
        if not variants:
            continue
        if variants == [canonical]:
            df = df.withColumn(canonical, col(canonical).cast(cast_type))
            continue
        # Other casing(s), possibly several in one micro-batch: coalesce
        # them into the canonical column instead of renaming (a rename
        # would collide).
        merged = coalesce(*[col(v).cast(cast_type) for v in variants])
        df = df.drop(*variants).withColumn(canonical, merged)
    return df


def get_dlt_table_name(full_name: str) -> str:
    """catalog.schema.table → schema.table (the pipeline's catalog is implied)."""
    parts = full_name.split(".")
    return f"{parts[1]}.{parts[2]}" if len(parts) == 3 else full_name


def apply_mappings(df, mappings):
    for m in mappings or []:
        df = df.withColumn(m["target_column"], expr(m["transform_rule"]))
    return df


def _split_expectations(rules):
    buckets = {"warn": {}, "drop": {}, "fail": {}}
    for r in rules or []:
        action = (r.get("action") or "warn").lower()
        if action not in buckets:
            raise ValueError(f"Expectation '{r.get('name')}': action must be warn|drop|fail")
        buckets[action][r["name"]] = r["constraint"]
    return buckets


def with_expectations(fn, rules):
    """Wraps the dataset function BEFORE dp.table/materialized_view is
    applied — expectations added after registration are silently lost."""
    b = _split_expectations(rules)
    if b["warn"]:
        fn = dp.expect_all(b["warn"])(fn)
    if b["drop"]:
        fn = dp.expect_all_or_drop(b["drop"])(fn)
    if b["fail"]:
        fn = dp.expect_all_or_fail(b["fail"])(fn)
    return fn


def _common_parent(paths):
    """initial/ and delta/ folders of one table share a parent. A streaming
    read accepts only one path, so those are read as one recursive stream."""
    norm = [p.rstrip("/") for p in paths if p.strip()]
    if len(norm) < 2:
        return None
    parents = {p.rsplit("/", 1)[0] for p in norm}
    return next(iter(parents)) + "/" if len(parents) == 1 else None


def _archive_dir(path: str) -> str:
    """cleanSource destination OUTSIDE the table folder. An archive inside a
    recursively-scanned folder would be picked up again as new files."""
    parts = path.rstrip("/").split("/")
    if parts[-1] in ("initial", "delta"):
        table_seg, base = parts[-2], "/".join(parts[:-2])
    else:
        table_seg, base = parts[-1], "/".join(parts[:-1])
    return f"{base}/_archive/{table_seg}/"

# COMMAND ----------

# ── 3. Bronze: Auto Loader over the SAP landing folders ──────────────────

BRONZE_TABLE_PROPERTIES = {
    "delta.feature.timestampNtz": "supported",
    "delta.columnMapping.mode":   "name",
    "delta.minReaderVersion":     "2",
    "delta.minWriterVersion":     "5",
}


def register_bronze(layer: dict):
    name   = layer["name"]
    source = layer.get("source") or {}
    if (layer.get("source_type") or "file") != "file" or source.get("type") != "autoloader":
        raise ValueError(f"Bronze '{name}': only SAP landing files (Auto Loader) are supported")

    target       = get_dlt_table_name(layer["target"]["table_name"])
    hints        = schema_to_hints(layer.get("schema"))
    clean_rules  = layer.get("clean_rules") or []
    expect_rules = layer.get("expect_rules") or []
    # Same path PipelineRegistry._clean_schema_locations() clears:
    # {base_volume}/schema/{layer_name}
    schema_root  = f"{BASE_VOLUME}/schema/{name}"

    raw_paths = [p.strip() for p in (source.get("path") or "").split(",") if p.strip()]
    if not raw_paths:
        raise ValueError(f"Bronze '{name}' has no source path")
    parent     = _common_parent(raw_paths)
    load_paths = [parent] if parent else raw_paths
    recursive  = bool(parent)

    def read(path: str, schema_location: str):
        reader = (
            spark.readStream.format("cloudFiles")
            .option("cloudFiles.format", source.get("format") or "parquet")
            .option("cloudFiles.schemaLocation", schema_location)
            .option("cloudFiles.schemaEvolutionMode", "rescue")
            .option("cloudFiles.cleanSource", "MOVE")
            .option("cloudFiles.cleanSource.moveDestination", _archive_dir(path))
            .option("cloudFiles.cleanSource.retentionDuration", ARCHIVE_AFTER)
        )
        if recursive:
            reader = reader.option("recursiveFileLookup", "true")
        if hints:
            reader = reader.option("cloudFiles.schemaHints", hints)
        df = normalize_system_columns(reader.load(path))
        df = df.select([f.name for f in df.schema.fields
                        if type(f.dataType).__name__ in SUPPORTED_TYPES])
        df = apply_mappings(df, clean_rules)
        return df.withColumn("_ingestion_time", current_timestamp())

    if len(load_paths) == 1:
        def _bronze():
            return read(load_paths[0], schema_root)

        dp.table(name=target, comment=f"Bronze — {name}",
                 table_properties=BRONZE_TABLE_PROPERTIES)(with_expectations(_bronze, expect_rules))
        log("BRONZE", f"{target} ← {load_paths[0]}" + (" (recursive)" if recursive else ""))
        return

    # Disjoint paths: one append flow per path into one streaming table.
    # Each flow needs its own schema location (two streams must not share
    # one); both sit under schema_root, so the registry still clears them.
    # Expectations go on the table, since flows don't take them.
    b = _split_expectations(expect_rules)
    dp.create_streaming_table(
        name=target, comment=f"Bronze — {name}",
        table_properties=BRONZE_TABLE_PROPERTIES,
        expect_all=b["warn"] or None,
        expect_all_or_drop=b["drop"] or None,
        expect_all_or_fail=b["fail"] or None,
    )
    for i, path in enumerate(load_paths):
        def _flow(path=path, i=i):   # default args bind this iteration's values
            return read(path, f"{schema_root}/flow_{i}")
        dp.append_flow(target=target, name=f"{target.split('.')[-1]}_flow_{i}")(_flow)
    log("BRONZE", f"{target} ← {len(load_paths)} paths (one append flow each)")

# COMMAND ----------

# ── 4. Silver: full / delta / scd1 / scd2 ────────────────────────────────

SILVER_TABLE_PROPERTIES = {"delta.feature.timestampNtz": "supported"}
# Columns that change on every load; SCD2 must not open a new version
# when only these differ.
SCD2_UNTRACKED_COLUMNS = ["_ingestion_time", "_rescued_data"]

BRONZE_BY_TARGET = {
    l["target"]["table_name"]: l for l in config["layers"] if l.get("dlt_mode") == "bronze"
}


def _silver_source(layer: dict) -> str:
    src = (layer.get("source") or {}).get("table_name")
    if not src:
        raise KeyError(f"Silver '{layer['name']}': source has no table_name — "
                       f"regenerate the config with the metadata loader.")
    return src


def _canonical(c):
    return c.lower() if c and c.lower() in SYSTEM_COL_CASTS else c


def _sequence_by(layer: dict, source_table: str):
    """__timestamp alone can tie for two changes to the same key. When the
    SAP metadata has a sequence column, order by (timestamp, sequence)."""
    wm = _canonical(layer.get("sequence_by"))
    if not wm:
        raise KeyError(f"Silver '{layer['name']}': no sequence_by in config")
    seq = _canonical(BRONZE_BY_TARGET.get(source_table, {}).get("sequence_col"))
    if seq and seq != wm:
        return struct(col(wm), col(seq)), f"struct({wm}, {seq})"
    return col(wm), wm


def register_silver_snapshot(layer: dict):
    """load_type=full: streaming mirror of bronze, every row kept as-is."""
    source_table = _silver_source(layer)
    target       = get_dlt_table_name(layer["target"]["table_name"])
    mappings     = (layer.get("transformations") or {}).get("mappings", [])

    def _silver():
        return apply_mappings(spark.readStream.table(source_table), mappings)

    dp.table(name=target, comment=f"Silver full — {layer['name']}",
             table_properties=SILVER_TABLE_PROPERTIES)(_silver)
    log("SILVER", f"{target} ← {source_table} (full mirror)")


def register_silver_delta(layer: dict):
    """load_type=delta: append-only incremental feed, no keys."""
    source_table = _silver_source(layer)
    target       = get_dlt_table_name(layer["target"]["table_name"])
    mappings     = (layer.get("transformations") or {}).get("mappings", [])
    wm           = _canonical(layer.get("sequence_by"))

    def _silver():
        df = spark.readStream.table(source_table)
        if wm:
            df = df.filter(col(wm).isNotNull())
        return apply_mappings(df, mappings)

    dp.table(name=target, comment=f"Silver delta — {layer['name']}",
             table_properties=SILVER_TABLE_PROPERTIES)(_silver)
    log("SILVER", f"{target} ← {source_table} (delta append)")


def register_silver_cdc(layer: dict, scd_type: int):
    """load_type=scd1 (upsert, latest row per key) or scd2 (full history)."""
    source_table = _silver_source(layer)
    target       = get_dlt_table_name(layer["target"]["table_name"])
    keys         = layer.get("keys") or []
    mappings     = (layer.get("transformations") or {}).get("mappings", [])
    delete_cond  = layer.get("delete_condition")
    if not keys:
        raise KeyError(f"Silver '{layer['name']}': SCD{scd_type} needs keys — the SAP "
                       f"metadata for this table has no primary key.")
    seq_col, seq_desc = _sequence_by(layer, source_table)

    cdc_source = source_table
    if mappings:
        # create_auto_cdc_flow takes a source NAME, so transforms go in a view.
        cdc_source = f"{target.split('.')[-1]}_pre_cdc"

        def _pre_cdc():
            return apply_mappings(spark.readStream.table(source_table), mappings)

        dp.temporary_view(name=cdc_source, comment=f"Pre-CDC transforms — {layer['name']}")(_pre_cdc)

    dp.create_streaming_table(name=target, comment=f"Silver SCD{scd_type} — {layer['name']}",
                              table_properties=SILVER_TABLE_PROPERTIES)
    kwargs = dict(target=target, source=cdc_source, keys=keys,
                  sequence_by=seq_col, stored_as_scd_type=scd_type)
    if delete_cond:
        kwargs["apply_as_deletes"] = expr(delete_cond)
    if scd_type == 2:
        kwargs["track_history_except_column_list"] = SCD2_UNTRACKED_COLUMNS
    dp.create_auto_cdc_flow(**kwargs)
    log("SILVER", f"{target} ← {source_table} (SCD{scd_type}, keys={keys}, "
                  f"sequence_by={seq_desc}, deletes={delete_cond or 'none'})")

# COMMAND ----------

# ── 5. Register bronze and silver layers ─────────────────────────────────────

SILVER_ROUTES = {
    "bronze":   register_bronze,
    "snapshot": register_silver_snapshot,
    "full":     register_silver_snapshot,   # configs generated before the dlt_mode fix
    "delta":    register_silver_delta,
    "upsert":   lambda l: register_silver_cdc(l, 1),
    "history":  lambda l: register_silver_cdc(l, 2),
}

layers = [l for l in config["layers"] if l.get("layer_type") == "dlt"]
n_gold = sum(1 for l in config["layers"] if l.get("layer_type") == "spark")
log("REGISTER", f"Registering {len(layers)} bronze/silver layer(s); "
                f"{n_gold} gold layer(s) left to the sap_gold notebook")

failures = []
for layer in layers:
    try:
        if layer.get("dlt_mode") == "bronze_join":
            log("REGISTER", f"Skipping bronze_join layer '{layer['name']}' (not used for SAP)")
        elif layer.get("dlt_mode") in SILVER_ROUTES:
            SILVER_ROUTES[layer["dlt_mode"]](layer)
        else:
            raise ValueError(f"unknown dlt_mode '{layer.get('dlt_mode')}'")
    except Exception as exc:
        reason = " ".join(str(exc).split())[:200]
        failures.append(f"{layer.get('name', '?')}: {reason}")
        log("REGISTER", f"FAILED {layer.get('name', '?')}: {exc}", "ERROR")

if failures:
    # One line: the run page truncates the error at the first newline.
    raise RuntimeError(f"{len(failures)} layer(s) failed to register — " + "  |  ".join(failures))

log("REGISTER", f"All {len(layers)} layer(s) registered. Log: {_LOG_FILE_PATH}")
